POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Joãozinho",
    "email": "joao@mail.com",
    "password": "123"
}

###

GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMyMzE3Njk4LCJleHAiOjE3MzIzMTgyOTh9.rrzE1YJg0KiHtgw8u5ABWiWXkrdnp4SdRz7Ptt-oaS4

###

GET http://localhost:3000/users/1

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "João da Silva"
}

###

DELETE http://localhost:3000/users/2